#!/usr/bin/env node
/**
 * inject-env.js
 * ─────────────────────────────────────────────────────────────
 * OPTIONAL build step. If SUPABASE_URL and SUPABASE_ANON_KEY are
 * set as environment variables (e.g. in the Vercel dashboard under
 * Project Settings → Environment Variables), this rewrites
 * js/config.js to use them instead of the committed defaults.
 *
 * If the env vars are NOT set, this script does nothing and the
 * committed defaults in js/config.js are used as-is — the site
 * works perfectly fine without ever running this script.
 *
 * Why you'd bother: it lets you point the exact same codebase at a
 * different Supabase project (e.g. a staging environment) purely
 * through Vercel env vars, with no code changes. Since the
 * Supabase anon key is a public, RLS-protected key (see the
 * comment in js/config.js), this is a convenience, not a security
 * requirement.
 *
 * Wired up as the "Build Command" in vercel.json:
 *   "buildCommand": "node scripts/inject-env.js"
 */
const fs = require('fs');
const path = require('path');

const SUPABASE_URL = process.env.SUPABASE_URL;
const SUPABASE_ANON_KEY = process.env.SUPABASE_ANON_KEY;

const configPath = path.join(__dirname, '..', 'js', 'config.js');

if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  console.log('[inject-env] SUPABASE_URL / SUPABASE_ANON_KEY not set — using committed defaults in js/config.js. Nothing to do.');
  process.exit(0);
}

const contents = `/* ═══════════════════════════════════════════════════════════════
   CONFIG (generated by scripts/inject-env.js at build time)
   ───────────────────────────────────────────────────────────────
   These values were injected from the SUPABASE_URL and
   SUPABASE_ANON_KEY environment variables set in the Vercel
   dashboard. Do not edit this file directly — edit the env vars
   instead and redeploy. See README.md for details.
═══════════════════════════════════════════════════════════════ */

export const SUPABASE_URL = ${JSON.stringify(SUPABASE_URL)};
export const SUPABASE_ANON_KEY = ${JSON.stringify(SUPABASE_ANON_KEY)};
`;

fs.writeFileSync(configPath, contents);
console.log('[inject-env] js/config.js written from environment variables.');
